volumes:
  medbid_db_data:
    external: false

secrets:
  postgres_user:
    file: secrets/postgres_user.txt
  postgres_password:
    file: secrets/postgres_password.txt

configs:
  keycloak_realm:
    file: medbid-realm.json

services:
  medbid-db:
    image: postgres:15.2
    container_name: medbid-db
    volumes:
      - "medbid_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - PGPORT=5432
    secrets:
      - postgres_user
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user)" ]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 1m30s